export enum Routes {
  authRouter = 'Auth.Router',
  mainRouter = 'Main.Router',
  welcome = 'welcome',
  register = 'register',
  login = 'Login.Screen',
  verification = 'verification',
  modalScreen = 'modalScreen',
  paymentScreensTab = 'paymentScreensTab',
  paymentMethod = 'paymentMethod',
  addnewcard = 'addnewcardscreen',
  createyourcard = 'createyourcard',
  yourCard = 'yourCardScreen',
  test = 'test',
}
